version: '3.4'

services:
  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongdb_data_container:/data/db
    networks:
      - kafkadotnet
  sql-server-db:
    image: mcr.microsoft.com/azure-sql-edge
    ports: 
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$tr0ngS@P@ssw0rd02
    volumes:
        - './drive:/var/opt/mssql'
    networks:
      - kafkadotnet
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkadotnet
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: unless-stopped
    networks:
      - kafkadotnet
    depends_on:
      - zookeeper

volumes:
  mongdb_data_container:
    driver: local
  sql-server-db:
    driver: local
networks:
  kafkadotnet:
    driver: bridge