version: '3.4'

services:
  mongodb_container:
    image: mongo:latest
    environment: 
      MONGO_INIT_ROOT_USERNAME: root
      MONGO_INIT_ROOT_PASSWORD: rootPassword
    ports:
      - "27017:27107"
    volumes:
      - mongdb_data_container:/data/db
    networks:
      - kafkadotnet
  sql-server-db:
    image: mcr.microsoft.com/azure-sql-edge
    ports: 
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$tr0ngS@P@ssw0rd02
    volumes:
        - './drive:/var/opt/mssql'
    networks:
      - kafkadotnet
  zookeeper:
    image: arm64v8/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafkadotnet
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - kafkadotnet
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongdb_data_container:
    driver: local
  sql-server-db:
    driver: local
networks:
  kafkadotnet:
    driver: bridge