version: '3.4'

services:
  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongdb_data_container:/data/db
    networks:
      - kafkadotnet
  sql-server-db:
    image: mcr.microsoft.com/azure-sql-edge
    ports: 
      - "1433:1433"
    environment: 
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=$tr0ngS@P@ssw0rd02"
    volumes:
        - './drive:/var/opt/mssql'
    networks:
      - kafkadotnet
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - kafkadotnet
volumes:
  mongdb_data_container:
    driver: local
  sql-server-db:
    driver: local
networks:
  kafkadotnet:
    driver: bridge